### ISSUE TITLE
[Minor] Headers within Headers

### ISSUE THREAD

**Issue by TheMaster99** [danneu/guild#11]
When you put a header within a header (no reason you should have to, but if for some reason you did) the size of the font appears to be added instead of set.

Example:
h1.size = 5 (random number)
h2.size = 3 (random number)

[h1]size 5 text [h2] size 8? text[/h2] size 5 text[/h1]

Example: http://prntscr.com/5ud3nd

**Comment by danneu** [comment]
Thanks. That's interesting.

Guess I misunderstood `em` sizing. I recreated the issue in JSFiddle: http://jsfiddle.net/danneu/8Ldchree/

**Comment by TheMaster99** [comment]
That works. I messed around with it and 100, 75, 50 px seem to be good numbers
http://jsfiddle.net/8Ldchree/4/

**Comment by danneu** [comment]
Cool. I'll play with the values as I'm getting ready to deploy BBCode to the prod server this weekend.

My goal with BBCode is to be as lenient as possible so that users don't need to get it 100% correct just to be able to submit their post. They can always fix it later.

But I will do my best to ensure that BBCode bugs can't be abused to be disruptive. Like, in this case, nesting enough headers to create 1000px text.

**Comment by danneu** [comment]
Ended up editing the CSS to hide nested header tags: https://github.com/danneu/guild/blob/91ab555e246b72a115b5538ae5eb86c6cff6225c/public/css/general.css#L235-L246
